### ISSUE TITLE
Stage nao checa corretamente fim de batalha com mais de 2 jogadores

### ISSUE THREAD

**Issue by rockrick1** [ArthurTui/mac0214#11]
assim que um jogador morre em uma partida com 3 ou 4 jogadores, deixando 2 ou 3 vivos, o jogo termina

**Comment by arthurtui** [comment]
Tentei reproduzir com 3 jogadores e não aconteceu nenhuma vez.

**Comment by arthurtui** [comment]
Consegui reproduzir, acontece quando o personagem toma mais de uma instância de dano antes de ser liberado, chamando o sinal de morte mais de uma vez. Coloquei uma flag pra consertar por agora, mas quando a morte for mais que apenas liberar o boneco da memória é bom rever isso.
