### ISSUE TITLE
Tower stage

### ISSUE THREAD

**Issue by arthurtui** [ArthurTui/mac0214#17]

**Comment by LuizGyro** [comment]
Hexagonal stage, with runes on the ground. At certain intervals of time, lightning strikes one of the symbols, stunning anyone nearby and lighting up the symbol. Once all symbols on the edge of the stage are lit up, they send electricity to the middle orb, that shoots it in various directions.

**Comment by arthurtui** [comment]
![new drawing](https://user-images.githubusercontent.com/2237750/44034309-2b7e00ee-9ee3-11e8-88de-d72d32ac93d2.png)
