### ISSUE TITLE
Popups, css and sss rework

### ISSUE THREAD

**Issue by arthurtui** [ArthurTui/mac0214#18]
Game interface should have a consistent style.

**Comment by LuizGyro** [comment]
Popup menus should have a scroll-like look, and open horizontally when opened

**Comment by LuizGyro** [comment]
On the CSS, each player would have and individual scroll, and when the player tries to enter, the scroll opens. There would be an actual background (image or effect, to be decided) instead of a black background.
There needs to be a rework on the controls on this menu too.

**Comment by LuizGyro** [comment]
On the SSS, we should remove the cursor, and the style should be consistent with the rest of the menus.
